spring:
  jersey:
    application-path: api
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: bpms
    password: password

camunda:
  admin-user-id: camunda
  admin-group-id: camunda-admin
  bpm:
    generic-properties:
      properties:
        enableHistoricInstancePermissions: true
    authorization:
      enabled: true
    admin-user:
      id: ${camunda.admin-user-id}
      password: camunda