server:
  port: 8080

camunda:
  admin-user-id: camunda
  admin-group-id: camunda-admin
  bpm:
    generic-properties:
      properties:
        enableHistoricInstancePermissions: true
        userResourceWhitelistPattern: '[a-zA-Z0-9_@.]+|camunda-admin'
    authorization:
      enabled: true

spring:
  jersey:
    application-path: api
  application:
    name: business-process-management
  sleuth:
    opentracing:
      enabled: true
    baggage:
      correlation-enabled: true
      correlation-fields: x-request-id
      remote-fields: x-request-id, x-access-token

# Configuration => prometheus.yml:
#   scrape_configs:
#     metrics_path: '/actuator/prometheus'
management:
  endpoints:
    web:
      exposure:
        include: '*'

ceph:
  bucket: ${CEPH_BUCKET_NAME:bucket}