server:
  port: 8080

spring:
  jersey:
    application-path: api
  application:
    name: business-process-management
    sleuth:
      opentracing:
        enabled: true
      baggage:
        correlation-enabled: true
        correlation-fields: x-request-id
        remote-fields: x-request-id

# Configuration => prometheus.yml:
#   scrape_configs:
#     metrics_path: '/actuator/prometheus'
management:
  endpoints:
    web:
      exposure:
        include: '*'

ceph:
  http-endpoint: ${CEPH_BUCKET_HOST:localhost}:${CEPH_BUCKET_PORT:8100}
  bucket: ${CEPH_BUCKET_NAME:bucket}