camunda:
  system-variables:
    dataFactoryBaseUrl: http://localhost:8877/mock-server
  bpm:
    job-execution:
      deployment-aware: true
    database:
      schema-update: true

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/camunda
    username: bpms
    password: password
