camunda:
  system-variables:
    dataFactoryBaseUrl: http://localhost:8877/mock-server
  bpm:
    authorization:
      enabled: false
    job-execution:
      deployment-aware: true
    database:
      schema-update: true
    admin-user:
      id: ${camunda.admin-user-id}
      password: camunda

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/camunda
    username: bpms
    password: password

logging:
  level:
    root: "info"
    org.springframework.web: "debug"
    ua.gov.mdtu.ddm.lowcode: "debug"
  file:
    name: ./logs/${spring.application.name}.log
  pattern:
    #    Logging patterns inherited from Spring Boot default logging system configuration
    console: '%d{${LOG_DATEFORMAT_PATTERN}} [trace:%X{traceId}/%X{spanId}/%X{x-request-id}] ${LOG_LEVEL_PATTERN} %pid --- [%15.15t] %-40.40c{1.} : %m%n${LOG_EXCEPTION_CONVERSION_WORD}'
    file: '%d{${LOG_DATEFORMAT_PATTERN}} ${LOG_LEVEL_PATTERN} %pid --- [%t] %-40.40c{1.} : %m%n${LOG_EXCEPTION_CONVERSION_WORD}'

ceph:
  http-endpoint: http://localhost:8100
  access-key: access-key
  secret-key: secret-key
  bucket: bucket