image:
  name: business-process-management
  version: latest
port: 8080
service:
  type: ClusterIP
  port: 8080
replicas: 1
appConfigMountPath: "/app/config/main"
camundaVarsMountPath: "/app/config/camunda"
appSecretsMountPath: "/app/secrets/main"
cephSecretMountPath: "/app/secrets/ceph"
prometheusScrapePath: "/actuator/prometheus"

db:
  url: citus-master
  port: 5432
  defaultDatabase: camunda
  secret: citus-secrets

ingress: # expose the service with a route or an ingress depending on platform type
  platform: openshift # openshift or kubernetes

ceph:
  bucketName: backend-ceph-bucket

monitoring:
  namespace: openshift-monitoring

javaOpts: "-Duser.timezone=UTC"