name: business-process-management
namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: apps.cicd.mdtu-ddm.projects.epam.com

database:
  required: false


ingress:
  required: false

image:
  name: business-process-management
  version: latest