image:
  name: business-process-management
  version: latest
port: 8080
service:
  type: ClusterIP
  port: 8080
replicas: 1
appConfigMountPath: "/app/config/main"
camundaVarsMountPath: "/app/config/camunda"
appSecretsMountPath: "/app/secrets"

db:
  image: postgres:9.6
  port: 5432
  service:
    type: ClusterIP
    port: 5432
    clusterIP: None
  replicas: 1
  defaultDatabase: camunda
  credentials:
    username: admin
    password: admin
  storage:
    size: 2Gi
    class: gp2-c
  podSecurityContext:
    runAsUser: 999
    fsGroup: 999

ingress: # expose the service with a route or an ingress depending on platform type
  platform: openshift # openshift or kubernetes
