spring:
  jersey:
    application-path: api
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: bpms
    password: password

camunda:
  admin-user-id: camunda
  admin-group-id: camunda-admin
  bpm:
    generic-properties:
      properties:
        enableHistoricInstancePermissions: true
    authorization:
      enabled: true
    admin-user:
      id: ${camunda.admin-user-id}
      password: camunda
  system-variables:
    const_dataFactoryBaseUrl: http://localhost:8877/mock-server
dso:
  url: http://localhost:8081

ceph:
  http-endpoint: http://localhost:8100
  access-key: access-key
  secret-key: secret-key
  bucket: bucket

user-settings-service-api:
  url: http://localhost:8878/user-settings-mock-server

keycloak:
  url: http://localhost:8082/auth
  realm: test-realm
  client-id:  client-id
  client-secret: client-secret
