{{- if eq .Values.deployProfile "dev" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  host: bpms-{{ .Values.cdPipelineName }}-{{ .Values.cdPipelineStageName }}.{{ .Values.dnsWildcard }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Chart.Name }}
    weight: 100
status:
  ingress: []
  {{- end }}
