apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-camunda-global-system-vars
  annotations:
    "helm.sh/hook": "pre-install"
data:
  # Values of this config map will be uploaded by registry regulations publication pipeline
  camunda-global-system-vars.yml: |-
