{{- if eq .Values.ingress.platform "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-path
spec:
  host: {{ .Values.cdPipelineName }}-{{ .Values.cdPipelineStageName }}.{{ .Values.dnsWildcard }}
  path: /api
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Chart.Name }}
    weight: 100
status:
  ingress: []
{{- end }}
