apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  application.yml: |-
    spring.datasource.driver-class-name: org.postgresql.Driver
    spring.datasource.url: jdbc:postgresql://{{ .Values.db.url }}:{{ .Values.db.port }}/{{ .Values.db.defaultDatabase }}
    spring.zipkin.baseUrl: http://zipkin.istio-system:9411
    camunda.bpm.job-execution.deployment-aware: true
    camunda.bpm.database.schema-update: true
    dso.url: http://digital-signature-ops:8080
    ceph.http-endpoint: https://s3-openshift-storage.{{ .Values.dnsWildcard }}
    keycloak.url: {{ template "keycloak.url" . }}/auth
    keycloak.citizen.realm: {{ template "keycloak.citizenTargetRealm" . }}
    keycloak.citizen.client-id: {{ .Values.keycloak.citizenClient.clientName }}
    keycloak.officer.realm: {{ template "keycloak.officerTargetRealm" . }}
    keycloak.officer.client-id: {{ .Values.keycloak.officerClient.clientName }}
    trembita-exchange-gateway: {{ toYaml .Values.trembitaExchangeGateway | nindent 6 }}
    ceph.file-storage-bucket:  {{ .Values.fileStorage.bucketName }}