apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  application.yml: |-
    spring.datasource.driver-class-name: org.postgresql.Driver
    spring.datasource.url: jdbc:postgresql://{{ .Chart.Name }}-db-headless:{{ .Values.db.service.port }}/{{ .Values.db.defaultDatabase }}

    camunda.bpm.job-execution.deployment-aware: true
    camunda.bpm.database.schema-update: true

    ceph.http-endpoint=${CEPH_BUCKET_HOST:localhost}:${CEPH_BUCKET_PORT:8100}
    ceph.bucket={{ .Values.ceph.bucketName }}