{{- $configmap := (lookup "v1" "ConfigMap" .Release.Namespace .Values.citizenConfigMapName) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.citizenConfigMapName }}
data:
  citizen-roles.yml: |-
  {{- if $configmap }}
    {{- index $configmap "data" "citizen-roles.yml" | nindent 4 }}
  {{- else }}
    roles:
      citizen
  {{- end -}}