kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    relatedNamespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Chart.Name }}
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60