{{- if not .Values.keycloak.citizenClient.public -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.keycloak.citizenClient.secretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.citizenClient.secretName }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ .Chart.Name }}
type: Opaque
  {{- if $secret }}
data:
  clientSecret: {{ $secret.data.clientSecret }}
  {{- else }}
stringData:
  {{- $clientSecret := uuidv4 | quote }}
  clientSecret: {{ $clientSecret }}
{{- end -}}
{{- end -}}
