kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.readSecretsRoleName }}
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - secrets
