spring:
  jersey:
    application-path: api
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: bpms
    password: password

camunda:
  admin-user-id: camunda
  admin-group-id: camunda-admin
  bpm:
    generic-properties:
      properties:
        enableHistoricInstancePermissions: true
    authorization:
      enabled: true
    admin-user:
      id: ${camunda.admin-user-id}
      password: camunda
    job-execution:
      enabled: false

data-platform:
  kafka:
    bootstrap: ${spring.embedded.kafka.brokers}
    consumer:
      enabled: true
      group-id: process-history-api
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      trusted-packages:
        - com.epam.digital.data.platform.bphistory.model
      custom-config:
        "[spring.deserializer.key.delegate.class]": org.apache.kafka.common.serialization.StringDeserializer
        "[spring.deserializer.value.delegate.class]": org.springframework.kafka.support.serializer.JsonDeserializer
        "[isolation.level]": read_committed
        "[enable.auto.commit]": false
    producer:
      enabled: true
      custom-config:
        "[transactional.id]": tx-${random.uuid}
        "[enable.idempotence]": true
    topic-properties:
      creation:
        enabled: false
        num-partitions: 2
        replication-factor: 1
    topics:
      history-process-instance-topic: bpm-history-process
      history-task-topic: bpm-history-task
    error-handler:
      initial-interval: 1500
      max-elapsed-time: 6000
      multiplier: 2

dso:
  url: http://localhost:8081

registry-rest-api:
  url: http://localhost:8877/mock-server

ceph:
  bucket: bucket

storage:
  form-data:
    type: redis
  message-payload:
    type: redis
  backend:
    redis:
      sentinel:
        master: mymaster
        nodes: 127.0.0.1:26379

user-settings-service:
  url: http://localhost:8878/user-settings-mock-server
excerpt-service-api:
  url: http://localhost:9999/excerpt-mock-service
digital-document-service:
  url: http://localhost:1111/digital-document-service-mock
keycloak:
  url: http://localhost:8200
  citizen:
    realm: citizen-realm
    client-id: citizen-client-id
    client-secret: citizen-client-secret
  officer:
    realm: officer-realm
    client-id: officer-client-id
    client-secret: officer-client-secret
  system-user:
    realm: system-user-realm
    client-id: system-user-client-id
    client-secret: system-user-client-secret

trembita:
  registries:
    edr-registry:
      url: http://localhost:7788/trembita-mock-server
      userId: DDM
      protocol-version: 4.0
      protocol: "SOAP"
      type: "platform"
      client:
        x-road-instance: CLIENT-TEST
        member-class: GOV
        member-code: 666777666
        subsystem-code: GOV_TEST
      service:
        x-road-instance: EDR-TEST
        member-class: GOV
        member-code: 11115888
        subsystem-code: EDR_test
      auth:
        type: "AUTH_TOKEN"
        secret:
          token: "auth_token"

registry-regulation:
  officer:
    roles:
      - name: task-dispatcher
      - name: head-officer

kubernetes:
  namespace:
    current: current-namespace