camunda:
  bpm:
    history-level: AUDIT
    history-publisher:
      kafka:
        enabled: true
        bootstrap: localhost:9092
        topics:
          history-process-instance-topic:
            name: bpm-history-process
          history-task-topic:
            name: bpm-history-task