camunda:
  bpm:
    database-history-level: NONE
data-platform:
  kafka:
    bootstrap: localhost:9092
    producer:
      enabled: true
    topic-properties:
      creation:
        enabled: true
        num-partitions: 1
        replication-factor: 1
    topics:
      history-process-instance-topic: bpm-history-process
      history-task-topic: bpm-history-task