camunda:
  bpm:
    history:
      level: NONE
    history-publisher:
      kafka:
        enabled: true
        bootstrap: localhost:9092
        topics:
          history-process-instance-topic:
            name: bpm-history-process
            num-partitions: 1
            replication-factor: 1
            retention-policy-in-days: 7
          history-task-topic:
            name: bpm-history-task
            num-partitions: 1
            replication-factor: 1
            retention-policy-in-days: 7