version: '3.1'

services:
  bpm-db:
    image: postgres:9.6
    container_name: bpm-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: camunda
      POSTGRES_USER: bpms
      POSTGRES_PASSWORD: password